/*
 * Copyright 2020-2022 JetBrains s.r.o. and Kotlin Deep Learning project contributors. All Rights Reserved.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE.txt file.
 */

package org.jetbrains.kotlinx.dl.api.core.models

import org.jetbrains.kotlinx.dl.api.core.Functional
import org.jetbrains.kotlinx.dl.api.core.activation.Activations
import org.jetbrains.kotlinx.dl.api.core.initializer.Constant
import org.jetbrains.kotlinx.dl.api.core.initializer.HeNormal
import org.jetbrains.kotlinx.dl.api.core.layer.convolutional.Conv2D
import org.jetbrains.kotlinx.dl.api.core.layer.convolutional.ConvPadding
import org.jetbrains.kotlinx.dl.api.core.layer.core.Dense
import org.jetbrains.kotlinx.dl.api.core.layer.core.Input
import org.jetbrains.kotlinx.dl.api.core.layer.freeze
import org.jetbrains.kotlinx.dl.api.core.layer.merge.Add
import org.jetbrains.kotlinx.dl.api.core.layer.pooling.GlobalAvgPool2D
import org.jetbrains.kotlinx.dl.api.core.layer.pooling.MaxPool2D
import org.jetbrains.kotlinx.dl.api.core.loss.Losses
import org.jetbrains.kotlinx.dl.api.core.metric.Accuracy
import org.jetbrains.kotlinx.dl.api.core.optimizer.Adam
import org.jetbrains.kotlinx.dl.api.core.shape.TensorShape
import org.jetbrains.kotlinx.dl.api.core.summary.LayerSummary
import org.jetbrains.kotlinx.dl.api.core.summary.ModelSummary
import org.jetbrains.kotlinx.dl.dataset.handler.NUMBER_OF_CLASSES
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

private const val NUM_CHANNELS = 1L
private const val IMAGE_SIZE = 28L
private const val SEED = 13L

internal class FunctionalModelTest {
    private val correctTestModel = Functional.of(
        input,
        conv2D_1(input),
        conv2D_2(conv2D_1),
        maxPool2D(conv2D_2),
        conv2D_4(maxPool2D),
        conv2D_5(conv2D_4),
        add(conv2D_5, maxPool2D),
        conv2D_6(add),
        conv2D_7(conv2D_6),
        add_1(conv2D_7, add),
        conv2D_8(add_1),
        globalAvgPool2D(conv2D_8),
        dense_1(globalAvgPool2D),
        dense_2(dense_1)
    ).apply {
        name = "functional_model"
    }

    private val correctTestModelWithUnsortedLayers = Functional.of(
        input,
        conv2D_2(conv2D_1),
        maxPool2D(conv2D_2),
        globalAvgPool2D(conv2D_8),
        dense_1(globalAvgPool2D),
        conv2D_1(input),
        conv2D_4(maxPool2D),
        conv2D_5(conv2D_4),
        add(conv2D_5, maxPool2D),
        conv2D_6(add),
        conv2D_7(conv2D_6),
        add_1(conv2D_7, add),
        conv2D_8(add_1),
        dense_2(dense_1)
    ).apply {
        name = "functional_model"
    }

    @Test
    fun summary() {
        dense_2.freeze()

        checkFunctionalModelAfterCompilation(correctTestModel)
        checkFunctionalModelAfterCompilation(correctTestModelWithUnsortedLayers)
    }

    private fun checkFunctionalModelAfterCompilation(model: Functional) {
        model.compile(
            optimizer = Adam(),
            loss = Losses.SOFT_MAX_CROSS_ENTROPY_WITH_LOGITS,
            metric = Accuracy()
        )

        assertEquals("functional_model", model.name)

        assertEquals(
            ModelSummary(
                type = "Functional",
                name = "functional_model",
                layersSummaries = listOf(
                    LayerSummary("input_1", "Input", TensorShape(-1, 28, 28, 1), 0, emptyList()),
                    LayerSummary("conv2D_1", "Conv2D", TensorShape(-1, 26, 26, 32), 320, listOf("input_1")),
                    LayerSummary("conv2D_2", "Conv2D", TensorShape(-1, 24, 24, 64), 18496, listOf("conv2D_1")),
                    LayerSummary("maxPool2D", "MaxPool2D", TensorShape(-1, 8, 8, 64), 0, listOf("conv2D_2")),
                    LayerSummary("conv2D_4", "Conv2D", TensorShape(-1, 8, 8, 64), 36928, listOf("maxPool2D")),
                    LayerSummary("conv2D_5", "Conv2D", TensorShape(-1, 8, 8, 64), 36928, listOf("conv2D_4")),
                    LayerSummary("add", "Add", TensorShape(-1, 8, 8, 64), 0, listOf("conv2D_5", "maxPool2D")),
                    LayerSummary("conv2D_6", "Conv2D", TensorShape(-1, 8, 8, 64), 36928, listOf("add")),
                    LayerSummary("conv2D_7", "Conv2D", TensorShape(-1, 8, 8, 64), 36928, listOf("conv2D_6")),
                    LayerSummary("add_1", "Add", TensorShape(-1, 8, 8, 64), 0, listOf("conv2D_7", "add")),
                    LayerSummary("conv2D_8", "Conv2D", TensorShape(-1, 6, 6, 64), 36928, listOf("add_1")),
                    LayerSummary("globalAvgPool2D", "GlobalAvgPool2D", TensorShape(-1, 64), 0, listOf("conv2D_8")),
                    LayerSummary("dense_1", "Dense", TensorShape(-1, 256), 16640, listOf("globalAvgPool2D")),
                    LayerSummary("dense_2", "Dense", TensorShape(-1, 10), 2570, listOf("dense_1"))
                ),
                trainableParamsCount = 220096,
                frozenParamsCount = 2570
            ),
            model.summary()
        )
    }
}

private val input = Input(
    IMAGE_SIZE,
    IMAGE_SIZE,
    NUM_CHANNELS,
    name = "input_1"
)
internal val conv2D_1 = Conv2D(
    filters = 32,
    kernelSize = intArrayOf(3, 3),
    strides = intArrayOf(1, 1, 1, 1),
    activation = Activations.Relu,
    kernelInitializer = HeNormal(SEED),
    biasInitializer = HeNormal(SEED),
    padding = ConvPadding.VALID,
    name = "conv2D_1"
)
internal val conv2D_2 = Conv2D(
    filters = 64,
    kernelSize = intArrayOf(3, 3),
    strides = intArrayOf(1, 1, 1, 1),
    activation = Activations.Relu,
    kernelInitializer = HeNormal(SEED),
    biasInitializer = HeNormal(SEED),
    padding = ConvPadding.VALID,
    name = "conv2D_2"
)
internal val maxPool2D = MaxPool2D(
    poolSize = intArrayOf(1, 3, 3, 1),
    strides = intArrayOf(1, 3, 3, 1),
    padding = ConvPadding.VALID,
    name = "maxPool2D"
)
internal val conv2D_4 = Conv2D(
    filters = 64,
    kernelSize = intArrayOf(3, 3),
    strides = intArrayOf(1, 1, 1, 1),
    activation = Activations.Relu,
    kernelInitializer = HeNormal(SEED),
    biasInitializer = HeNormal(SEED),
    padding = ConvPadding.SAME,
    name = "conv2D_4"
)
internal val conv2D_5 = Conv2D(
    filters = 64,
    kernelSize = intArrayOf(3, 3),
    strides = intArrayOf(1, 1, 1, 1),
    activation = Activations.Relu,
    kernelInitializer = HeNormal(SEED),
    biasInitializer = HeNormal(SEED),
    padding = ConvPadding.SAME,
    name = "conv2D_5"
)
internal val add = Add(name = "add")
internal val conv2D_6 = Conv2D(
    filters = 64,
    kernelSize = intArrayOf(3, 3),
    strides = intArrayOf(1, 1, 1, 1),
    activation = Activations.Relu,
    kernelInitializer = HeNormal(SEED),
    biasInitializer = HeNormal(SEED),
    padding = ConvPadding.SAME,
    name = "conv2D_6"
)
internal val conv2D_7 = Conv2D(
    filters = 64,
    kernelSize = intArrayOf(3, 3),
    strides = intArrayOf(1, 1, 1, 1),
    activation = Activations.Relu,
    kernelInitializer = HeNormal(SEED),
    biasInitializer = HeNormal(SEED),
    padding = ConvPadding.SAME,
    name = "conv2D_7"
)
internal val add_1 = Add(name = "add_1")
internal val conv2D_8 = Conv2D(
    filters = 64,
    kernelSize = intArrayOf(3, 3),
    strides = intArrayOf(1, 1, 1, 1),
    activation = Activations.Relu,
    kernelInitializer = HeNormal(SEED),
    biasInitializer = HeNormal(SEED),
    padding = ConvPadding.VALID,
    name = "conv2D_8"
)
internal val globalAvgPool2D = GlobalAvgPool2D(name = "globalAvgPool2D")
internal val dense_1 = Dense(
    outputSize = 256,
    activation = Activations.Relu,
    kernelInitializer = HeNormal(SEED),
    biasInitializer = Constant(0.1f),
    name = "dense_1"
)
internal val dense_2 = Dense(
    outputSize = NUMBER_OF_CLASSES,
    activation = Activations.Linear,
    kernelInitializer = HeNormal(SEED),
    biasInitializer = Constant(0.1f),
    name = "dense_2"
)

private val graphLines = setOf(
    "Name: default_data_placeholder; Type: Placeholder; Out #tensors:  1",
    "Name: conv2D_1_conv2d_kernel; Type: VariableV2; Out #tensors:  1",
    "Name: conv2D_1_conv2d_bias; Type: VariableV2; Out #tensors:  1",
    "Name: Const; Type: Const; Out #tensors:  1",
    "Name: Const_1; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_2; Type: Const; Out #tensors:  1",
    "Name: Cast; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_1_conv2d_kernel; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_1_conv2d_kernel; Type: Assign; Out #tensors:  1",
    "Name: Const_3; Type: Const; Out #tensors:  1",
    "Name: Const_4; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_1; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_5; Type: Const; Out #tensors:  1",
    "Name: Cast_1; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_1_conv2d_bias; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_1_conv2d_bias; Type: Assign; Out #tensors:  1",
    "Name: conv2D_2_conv2d_kernel; Type: VariableV2; Out #tensors:  1",
    "Name: conv2D_2_conv2d_bias; Type: VariableV2; Out #tensors:  1",
    "Name: Const_6; Type: Const; Out #tensors:  1",
    "Name: Const_7; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_2; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_8; Type: Const; Out #tensors:  1",
    "Name: Cast_2; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_2_conv2d_kernel; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_2_conv2d_kernel; Type: Assign; Out #tensors:  1",
    "Name: Const_9; Type: Const; Out #tensors:  1",
    "Name: Const_10; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_3; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_11; Type: Const; Out #tensors:  1",
    "Name: Cast_3; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_2_conv2d_bias; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_2_conv2d_bias; Type: Assign; Out #tensors:  1",
    "Name: conv2D_4_conv2d_kernel; Type: VariableV2; Out #tensors:  1",
    "Name: conv2D_4_conv2d_bias; Type: VariableV2; Out #tensors:  1",
    "Name: Const_12; Type: Const; Out #tensors:  1",
    "Name: Const_13; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_4; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_14; Type: Const; Out #tensors:  1",
    "Name: Cast_4; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_4_conv2d_kernel; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_4_conv2d_kernel; Type: Assign; Out #tensors:  1",
    "Name: Const_15; Type: Const; Out #tensors:  1",
    "Name: Const_16; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_5; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_17; Type: Const; Out #tensors:  1",
    "Name: Cast_5; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_4_conv2d_bias; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_4_conv2d_bias; Type: Assign; Out #tensors:  1",
    "Name: conv2D_5_conv2d_kernel; Type: VariableV2; Out #tensors:  1",
    "Name: conv2D_5_conv2d_bias; Type: VariableV2; Out #tensors:  1",
    "Name: Const_18; Type: Const; Out #tensors:  1",
    "Name: Const_19; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_6; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_20; Type: Const; Out #tensors:  1",
    "Name: Cast_6; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_5_conv2d_kernel; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_5_conv2d_kernel; Type: Assign; Out #tensors:  1",
    "Name: Const_21; Type: Const; Out #tensors:  1",
    "Name: Const_22; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_7; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_23; Type: Const; Out #tensors:  1",
    "Name: Cast_7; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_5_conv2d_bias; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_5_conv2d_bias; Type: Assign; Out #tensors:  1",
    "Name: conv2D_6_conv2d_kernel; Type: VariableV2; Out #tensors:  1",
    "Name: conv2D_6_conv2d_bias; Type: VariableV2; Out #tensors:  1",
    "Name: Const_24; Type: Const; Out #tensors:  1",
    "Name: Const_25; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_8; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_26; Type: Const; Out #tensors:  1",
    "Name: Cast_8; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_6_conv2d_kernel; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_6_conv2d_kernel; Type: Assign; Out #tensors:  1",
    "Name: Const_27; Type: Const; Out #tensors:  1",
    "Name: Const_28; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_9; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_29; Type: Const; Out #tensors:  1",
    "Name: Cast_9; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_6_conv2d_bias; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_6_conv2d_bias; Type: Assign; Out #tensors:  1",
    "Name: conv2D_7_conv2d_kernel; Type: VariableV2; Out #tensors:  1",
    "Name: conv2D_7_conv2d_bias; Type: VariableV2; Out #tensors:  1",
    "Name: Const_30; Type: Const; Out #tensors:  1",
    "Name: Const_31; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_10; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_32; Type: Const; Out #tensors:  1",
    "Name: Cast_10; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_7_conv2d_kernel; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_7_conv2d_kernel; Type: Assign; Out #tensors:  1",
    "Name: Const_33; Type: Const; Out #tensors:  1",
    "Name: Const_34; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_11; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_35; Type: Const; Out #tensors:  1",
    "Name: Cast_11; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_7_conv2d_bias; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_7_conv2d_bias; Type: Assign; Out #tensors:  1",
    "Name: conv2D_8_conv2d_kernel; Type: VariableV2; Out #tensors:  1",
    "Name: conv2D_8_conv2d_bias; Type: VariableV2; Out #tensors:  1",
    "Name: Const_36; Type: Const; Out #tensors:  1",
    "Name: Const_37; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_12; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_38; Type: Const; Out #tensors:  1",
    "Name: Cast_12; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_8_conv2d_kernel; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_8_conv2d_kernel; Type: Assign; Out #tensors:  1",
    "Name: Const_39; Type: Const; Out #tensors:  1",
    "Name: Const_40; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_13; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_41; Type: Const; Out #tensors:  1",
    "Name: Cast_13; Type: Cast; Out #tensors:  1",
    "Name: Init_conv2D_8_conv2d_bias; Type: Mul; Out #tensors:  1",
    "Name: Assign_conv2D_8_conv2d_bias; Type: Assign; Out #tensors:  1",
    "Name: dense_1_dense_kernel; Type: VariableV2; Out #tensors:  1",
    "Name: dense_1_dense_bias; Type: VariableV2; Out #tensors:  1",
    "Name: Const_42; Type: Const; Out #tensors:  1",
    "Name: Const_43; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_14; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_44; Type: Const; Out #tensors:  1",
    "Name: Cast_14; Type: Cast; Out #tensors:  1",
    "Name: Init_dense_1_dense_kernel; Type: Mul; Out #tensors:  1",
    "Name: Assign_dense_1_dense_kernel; Type: Assign; Out #tensors:  1",
    "Name: Const_45; Type: Const; Out #tensors:  1",
    "Name: Const_46; Type: Const; Out #tensors:  1",
    "Name: Init_dense_1_dense_bias; Type: Fill; Out #tensors:  1",
    "Name: Assign_dense_1_dense_bias; Type: Assign; Out #tensors:  1",
    "Name: dense_2_dense_kernel; Type: VariableV2; Out #tensors:  1",
    "Name: dense_2_dense_bias; Type: VariableV2; Out #tensors:  1",
    "Name: Const_47; Type: Const; Out #tensors:  1",
    "Name: Const_48; Type: Const; Out #tensors:  1",
    "Name: StatelessTruncatedNormal_15; Type: StatelessTruncatedNormal; Out #tensors:  1",
    "Name: Const_49; Type: Const; Out #tensors:  1",
    "Name: Cast_15; Type: Cast; Out #tensors:  1",
    "Name: Init_dense_2_dense_kernel; Type: Mul; Out #tensors:  1",
    "Name: Assign_dense_2_dense_kernel; Type: Assign; Out #tensors:  1",
    "Name: Const_50; Type: Const; Out #tensors:  1",
    "Name: Const_51; Type: Const; Out #tensors:  1",
    "Name: Init_dense_2_dense_bias; Type: Fill; Out #tensors:  1",
    "Name: Assign_dense_2_dense_bias; Type: Assign; Out #tensors:  1",
    "Name: Placeholder; Type: Placeholder; Out #tensors:  1",
    "Name: numberOfLosses; Type: Placeholder; Out #tensors:  1",
    "Name: training; Type: Placeholder; Out #tensors:  1",
    "Name: Conv2d; Type: Conv2D; Out #tensors:  1",
    "Name: BiasAdd; Type: BiasAdd; Out #tensors:  1",
    "Name: Relu; Type: Relu; Out #tensors:  1",
    "Name: Activation_conv2D_1; Type: Identity; Out #tensors:  1",
    "Name: Conv2d_1; Type: Conv2D; Out #tensors:  1",
    "Name: BiasAdd_1; Type: BiasAdd; Out #tensors:  1",
    "Name: Relu_1; Type: Relu; Out #tensors:  1",
    "Name: Activation_conv2D_2; Type: Identity; Out #tensors:  1",
    "Name: Const_52; Type: Const; Out #tensors:  1",
    "Name: Const_53; Type: Const; Out #tensors:  1",
    "Name: MaxPool; Type: MaxPoolV2; Out #tensors:  1",
    "Name: Conv2d_2; Type: Conv2D; Out #tensors:  1",
    "Name: BiasAdd_2; Type: BiasAdd; Out #tensors:  1",
    "Name: Relu_2; Type: Relu; Out #tensors:  1",
    "Name: Activation_conv2D_4; Type: Identity; Out #tensors:  1",
    "Name: Conv2d_3; Type: Conv2D; Out #tensors:  1",
    "Name: BiasAdd_3; Type: BiasAdd; Out #tensors:  1",
    "Name: Relu_3; Type: Relu; Out #tensors:  1",
    "Name: Activation_conv2D_5; Type: Identity; Out #tensors:  1",
    "Name: Add; Type: Add; Out #tensors:  1",
    "Name: AddLayer; Type: Identity; Out #tensors:  1",
    "Name: Conv2d_4; Type: Conv2D; Out #tensors:  1",
    "Name: BiasAdd_4; Type: BiasAdd; Out #tensors:  1",
    "Name: Relu_4; Type: Relu; Out #tensors:  1",
    "Name: Activation_conv2D_6; Type: Identity; Out #tensors:  1",
    "Name: Conv2d_5; Type: Conv2D; Out #tensors:  1",
    "Name: BiasAdd_5; Type: BiasAdd; Out #tensors:  1",
    "Name: Relu_5; Type: Relu; Out #tensors:  1",
    "Name: Activation_conv2D_7; Type: Identity; Out #tensors:  1",
    "Name: Add_1; Type: Add; Out #tensors:  1",
    "Name: AddLayer_1; Type: Identity; Out #tensors:  1",
    "Name: Conv2d_6; Type: Conv2D; Out #tensors:  1",
    "Name: BiasAdd_6; Type: BiasAdd; Out #tensors:  1",
    "Name: Relu_6; Type: Relu; Out #tensors:  1",
    "Name: Activation_conv2D_8; Type: Identity; Out #tensors:  1",
    "Name: Const_54; Type: Const; Out #tensors:  1",
    "Name: Mean; Type: Mean; Out #tensors:  1",
    "Name: MatMul; Type: MatMul; Out #tensors:  1",
    "Name: Add_2; Type: Add; Out #tensors:  1",
    "Name: Relu_7; Type: Relu; Out #tensors:  1",
    "Name: Activation_dense_1; Type: Identity; Out #tensors:  1",
    "Name: MatMul_1; Type: MatMul; Out #tensors:  1",
    "Name: Add_3; Type: Add; Out #tensors:  1",
    "Name: Activation_dense_2; Type: Identity; Out #tensors:  1",
    "Name: SoftmaxCrossEntropyWithLogits; Type: SoftmaxCrossEntropyWithLogits; Out #tensors:  2",
    "Name: Const_55; Type: Const; Out #tensors:  1",
    "Name: Mean_1; Type: Mean; Out #tensors:  1",
    "Name: default_training_loss; Type: Identity; Out #tensors:  1",
    "Name: Gradients/OnesLike; Type: OnesLike; Out #tensors:  1",
    "Name: Gradients/Identity; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Const; Type: Const; Out #tensors:  1",
    "Name: Gradients/Const_1; Type: Const; Out #tensors:  1",
    "Name: Gradients/Size; Type: Size; Out #tensors:  1",
    "Name: Gradients/Add; Type: Add; Out #tensors:  1",
    "Name: Gradients/Mod; Type: Mod; Out #tensors:  1",
    "Name: Gradients/Range; Type: Range; Out #tensors:  1",
    "Name: Gradients/OnesLike_1; Type: OnesLike; Out #tensors:  1",
    "Name: Gradients/DynamicStitch; Type: DynamicStitch; Out #tensors:  1",
    "Name: Gradients/Const_2; Type: Const; Out #tensors:  1",
    "Name: Gradients/Maximum; Type: Maximum; Out #tensors:  1",
    "Name: Gradients/Div; Type: Div; Out #tensors:  1",
    "Name: Gradients/Reshape; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/Tile; Type: Tile; Out #tensors:  1",
    "Name: Gradients/Shape_1; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Shape_2; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Const_3; Type: Const; Out #tensors:  1",
    "Name: Gradients/Prod; Type: Prod; Out #tensors:  1",
    "Name: Gradients/Prod_1; Type: Prod; Out #tensors:  1",
    "Name: Gradients/Const_4; Type: Const; Out #tensors:  1",
    "Name: Gradients/Maximum_1; Type: Maximum; Out #tensors:  1",
    "Name: Gradients/Div_1; Type: Div; Out #tensors:  1",
    "Name: Gradients/Cast; Type: Cast; Out #tensors:  1",
    "Name: Gradients/Div_2; Type: Div; Out #tensors:  1",
    "Name: Gradients/ZerosLike; Type: ZerosLike; Out #tensors:  1",
    "Name: Gradients/Const_5/Const; Type: Const; Out #tensors:  1",
    "Name: Gradients/ExpandDims; Type: ExpandDims; Out #tensors:  1",
    "Name: Gradients/Multiply; Type: Mul; Out #tensors:  1",
    "Name: Gradients/LogSoftmax; Type: LogSoftmax; Out #tensors:  1",
    "Name: Gradients/Const_6/Const; Type: Const; Out #tensors:  1",
    "Name: Gradients/Multiply_1; Type: Mul; Out #tensors:  1",
    "Name: Gradients/Const_7/Const; Type: Const; Out #tensors:  1",
    "Name: Gradients/ExpandDims_1; Type: ExpandDims; Out #tensors:  1",
    "Name: Gradients/Multiply_2; Type: Mul; Out #tensors:  1",
    "Name: Gradients/Identity_1; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Identity_2; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Identity_3; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_3; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Shape_4; Type: Shape; Out #tensors:  1",
    "Name: Gradients/BroadcastGradientArgs; Type: BroadcastGradientArgs; Out #tensors:  2",
    "Name: Gradients/Sum; Type: Sum; Out #tensors:  1",
    "Name: Gradients/Reshape_1; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/Sum_1; Type: Sum; Out #tensors:  1",
    "Name: Gradients/Reshape_2; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/MatMul; Type: MatMul; Out #tensors:  1",
    "Name: Gradients/MatMul_1; Type: MatMul; Out #tensors:  1",
    "Name: Gradients/Identity_4; Type: Identity; Out #tensors:  1",
    "Name: Gradients/ReluGrad; Type: ReluGrad; Out #tensors:  1",
    "Name: Gradients/Identity_5; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Identity_6; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_5; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Shape_6; Type: Shape; Out #tensors:  1",
    "Name: Gradients/BroadcastGradientArgs_1; Type: BroadcastGradientArgs; Out #tensors:  2",
    "Name: Gradients/Sum_2; Type: Sum; Out #tensors:  1",
    "Name: Gradients/Reshape_3; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/Sum_3; Type: Sum; Out #tensors:  1",
    "Name: Gradients/Reshape_4; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/MatMul_2; Type: MatMul; Out #tensors:  1",
    "Name: Gradients/MatMul_3; Type: MatMul; Out #tensors:  1",
    "Name: Gradients/Shape_7; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Const_8; Type: Const; Out #tensors:  1",
    "Name: Gradients/Const_9; Type: Const; Out #tensors:  1",
    "Name: Gradients/Size_1; Type: Size; Out #tensors:  1",
    "Name: Gradients/Add_1; Type: Add; Out #tensors:  1",
    "Name: Gradients/Mod_1; Type: Mod; Out #tensors:  1",
    "Name: Gradients/Range_1; Type: Range; Out #tensors:  1",
    "Name: Gradients/OnesLike_2; Type: OnesLike; Out #tensors:  1",
    "Name: Gradients/DynamicStitch_1; Type: DynamicStitch; Out #tensors:  1",
    "Name: Gradients/Const_10; Type: Const; Out #tensors:  1",
    "Name: Gradients/Maximum_2; Type: Maximum; Out #tensors:  1",
    "Name: Gradients/Div_3; Type: Div; Out #tensors:  1",
    "Name: Gradients/Reshape_5; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/Tile_1; Type: Tile; Out #tensors:  1",
    "Name: Gradients/Shape_8; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Shape_9; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Const_11; Type: Const; Out #tensors:  1",
    "Name: Gradients/Prod_2; Type: Prod; Out #tensors:  1",
    "Name: Gradients/Prod_3; Type: Prod; Out #tensors:  1",
    "Name: Gradients/Const_12; Type: Const; Out #tensors:  1",
    "Name: Gradients/Maximum_3; Type: Maximum; Out #tensors:  1",
    "Name: Gradients/Div_4; Type: Div; Out #tensors:  1",
    "Name: Gradients/Cast_1; Type: Cast; Out #tensors:  1",
    "Name: Gradients/Div_5; Type: Div; Out #tensors:  1",
    "Name: Gradients/Identity_7; Type: Identity; Out #tensors:  1",
    "Name: Gradients/ReluGrad_1; Type: ReluGrad; Out #tensors:  1",
    "Name: Gradients/BiasAddGrad; Type: BiasAddGrad; Out #tensors:  1",
    "Name: Gradients/Identity_8; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_10; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropInput; Type: Conv2DBackpropInput; Out #tensors:  1",
    "Name: Gradients/Shape_11; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropFilter; Type: Conv2DBackpropFilter; Out #tensors:  1",
    "Name: Gradients/Identity_9; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Identity_10; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Identity_11; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_12; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Shape_13; Type: Shape; Out #tensors:  1",
    "Name: Gradients/BroadcastGradientArgs_2; Type: BroadcastGradientArgs; Out #tensors:  2",
    "Name: Gradients/Sum_4; Type: Sum; Out #tensors:  1",
    "Name: Gradients/Reshape_6; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/Sum_5; Type: Sum; Out #tensors:  1",
    "Name: Gradients/Reshape_7; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/Identity_12; Type: Identity; Out #tensors:  1",
    "Name: Gradients/ReluGrad_2; Type: ReluGrad; Out #tensors:  1",
    "Name: Gradients/BiasAddGrad_1; Type: BiasAddGrad; Out #tensors:  1",
    "Name: Gradients/Identity_13; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_14; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropInput_1; Type: Conv2DBackpropInput; Out #tensors:  1",
    "Name: Gradients/Shape_15; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropFilter_1; Type: Conv2DBackpropFilter; Out #tensors:  1",
    "Name: Gradients/Identity_14; Type: Identity; Out #tensors:  1",
    "Name: Gradients/ReluGrad_3; Type: ReluGrad; Out #tensors:  1",
    "Name: Gradients/BiasAddGrad_2; Type: BiasAddGrad; Out #tensors:  1",
    "Name: Gradients/Identity_15; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_16; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropInput_2; Type: Conv2DBackpropInput; Out #tensors:  1",
    "Name: Gradients/Shape_17; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropFilter_2; Type: Conv2DBackpropFilter; Out #tensors:  1",
    "Name: Gradients/AddN; Type: AddN; Out #tensors:  1",
    "Name: Gradients/Identity_16; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Identity_17; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Identity_18; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_18; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Shape_19; Type: Shape; Out #tensors:  1",
    "Name: Gradients/BroadcastGradientArgs_3; Type: BroadcastGradientArgs; Out #tensors:  2",
    "Name: Gradients/Sum_6; Type: Sum; Out #tensors:  1",
    "Name: Gradients/Reshape_8; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/Sum_7; Type: Sum; Out #tensors:  1",
    "Name: Gradients/Reshape_9; Type: Reshape; Out #tensors:  1",
    "Name: Gradients/Identity_19; Type: Identity; Out #tensors:  1",
    "Name: Gradients/ReluGrad_4; Type: ReluGrad; Out #tensors:  1",
    "Name: Gradients/BiasAddGrad_3; Type: BiasAddGrad; Out #tensors:  1",
    "Name: Gradients/Identity_20; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_20; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropInput_3; Type: Conv2DBackpropInput; Out #tensors:  1",
    "Name: Gradients/Shape_21; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropFilter_3; Type: Conv2DBackpropFilter; Out #tensors:  1",
    "Name: Gradients/Identity_21; Type: Identity; Out #tensors:  1",
    "Name: Gradients/ReluGrad_5; Type: ReluGrad; Out #tensors:  1",
    "Name: Gradients/BiasAddGrad_4; Type: BiasAddGrad; Out #tensors:  1",
    "Name: Gradients/Identity_22; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_22; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropInput_4; Type: Conv2DBackpropInput; Out #tensors:  1",
    "Name: Gradients/Shape_23; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropFilter_4; Type: Conv2DBackpropFilter; Out #tensors:  1",
    "Name: Gradients/AddN_1; Type: AddN; Out #tensors:  1",
    "Name: Gradients/MaxPoolGradV2; Type: MaxPoolGradV2; Out #tensors:  1",
    "Name: Gradients/Identity_23; Type: Identity; Out #tensors:  1",
    "Name: Gradients/ReluGrad_6; Type: ReluGrad; Out #tensors:  1",
    "Name: Gradients/BiasAddGrad_5; Type: BiasAddGrad; Out #tensors:  1",
    "Name: Gradients/Identity_24; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_24; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropInput_5; Type: Conv2DBackpropInput; Out #tensors:  1",
    "Name: Gradients/Shape_25; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropFilter_5; Type: Conv2DBackpropFilter; Out #tensors:  1",
    "Name: Gradients/Identity_25; Type: Identity; Out #tensors:  1",
    "Name: Gradients/ReluGrad_7; Type: ReluGrad; Out #tensors:  1",
    "Name: Gradients/BiasAddGrad_6; Type: BiasAddGrad; Out #tensors:  1",
    "Name: Gradients/Identity_26; Type: Identity; Out #tensors:  1",
    "Name: Gradients/Shape_26; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropInput_6; Type: Conv2DBackpropInput; Out #tensors:  1",
    "Name: Gradients/Shape_27; Type: Shape; Out #tensors:  1",
    "Name: Gradients/Conv2DBackpropFilter_6; Type: Conv2DBackpropFilter; Out #tensors:  1",
    "Name: Shape; Type: Shape; Out #tensors:  1",
    "Name: Const_56; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_1_conv2d_kernel-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_1_conv2d_kernel-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_1_conv2d_kernel-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_1; Type: Shape; Out #tensors:  1",
    "Name: Const_57; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_1_conv2d_kernel-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_1_conv2d_kernel-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_1_conv2d_kernel-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_2; Type: Shape; Out #tensors:  1",
    "Name: Const_58; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_1_conv2d_bias-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_1_conv2d_bias-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_1_conv2d_bias-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_3; Type: Shape; Out #tensors:  1",
    "Name: Const_59; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_1_conv2d_bias-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_1_conv2d_bias-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_1_conv2d_bias-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_4; Type: Shape; Out #tensors:  1",
    "Name: Const_60; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_2_conv2d_kernel-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_2_conv2d_kernel-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_2_conv2d_kernel-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_5; Type: Shape; Out #tensors:  1",
    "Name: Const_61; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_2_conv2d_kernel-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_2_conv2d_kernel-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_2_conv2d_kernel-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_6; Type: Shape; Out #tensors:  1",
    "Name: Const_62; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_2_conv2d_bias-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_2_conv2d_bias-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_2_conv2d_bias-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_7; Type: Shape; Out #tensors:  1",
    "Name: Const_63; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_2_conv2d_bias-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_2_conv2d_bias-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_2_conv2d_bias-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_8; Type: Shape; Out #tensors:  1",
    "Name: Const_64; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_4_conv2d_kernel-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_4_conv2d_kernel-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_4_conv2d_kernel-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_9; Type: Shape; Out #tensors:  1",
    "Name: Const_65; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_4_conv2d_kernel-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_4_conv2d_kernel-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_4_conv2d_kernel-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_10; Type: Shape; Out #tensors:  1",
    "Name: Const_66; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_4_conv2d_bias-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_4_conv2d_bias-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_4_conv2d_bias-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_11; Type: Shape; Out #tensors:  1",
    "Name: Const_67; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_4_conv2d_bias-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_4_conv2d_bias-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_4_conv2d_bias-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_12; Type: Shape; Out #tensors:  1",
    "Name: Const_68; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_5_conv2d_kernel-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_5_conv2d_kernel-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_5_conv2d_kernel-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_13; Type: Shape; Out #tensors:  1",
    "Name: Const_69; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_5_conv2d_kernel-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_5_conv2d_kernel-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_5_conv2d_kernel-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_14; Type: Shape; Out #tensors:  1",
    "Name: Const_70; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_5_conv2d_bias-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_5_conv2d_bias-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_5_conv2d_bias-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_15; Type: Shape; Out #tensors:  1",
    "Name: Const_71; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_5_conv2d_bias-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_5_conv2d_bias-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_5_conv2d_bias-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_16; Type: Shape; Out #tensors:  1",
    "Name: Const_72; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_6_conv2d_kernel-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_6_conv2d_kernel-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_6_conv2d_kernel-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_17; Type: Shape; Out #tensors:  1",
    "Name: Const_73; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_6_conv2d_kernel-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_6_conv2d_kernel-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_6_conv2d_kernel-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_18; Type: Shape; Out #tensors:  1",
    "Name: Const_74; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_6_conv2d_bias-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_6_conv2d_bias-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_6_conv2d_bias-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_19; Type: Shape; Out #tensors:  1",
    "Name: Const_75; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_6_conv2d_bias-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_6_conv2d_bias-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_6_conv2d_bias-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_20; Type: Shape; Out #tensors:  1",
    "Name: Const_76; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_7_conv2d_kernel-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_7_conv2d_kernel-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_7_conv2d_kernel-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_21; Type: Shape; Out #tensors:  1",
    "Name: Const_77; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_7_conv2d_kernel-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_7_conv2d_kernel-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_7_conv2d_kernel-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_22; Type: Shape; Out #tensors:  1",
    "Name: Const_78; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_7_conv2d_bias-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_7_conv2d_bias-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_7_conv2d_bias-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_23; Type: Shape; Out #tensors:  1",
    "Name: Const_79; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_7_conv2d_bias-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_7_conv2d_bias-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_7_conv2d_bias-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_24; Type: Shape; Out #tensors:  1",
    "Name: Const_80; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_8_conv2d_kernel-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_8_conv2d_kernel-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_8_conv2d_kernel-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_25; Type: Shape; Out #tensors:  1",
    "Name: Const_81; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_8_conv2d_kernel-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_8_conv2d_kernel-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_8_conv2d_kernel-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_26; Type: Shape; Out #tensors:  1",
    "Name: Const_82; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_8_conv2d_bias-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_8_conv2d_bias-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_8_conv2d_bias-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_27; Type: Shape; Out #tensors:  1",
    "Name: Const_83; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_conv2D_8_conv2d_bias-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_conv2D_8_conv2d_bias-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_conv2D_8_conv2d_bias-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_28; Type: Shape; Out #tensors:  1",
    "Name: Const_84; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_dense_1_dense_kernel-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_dense_1_dense_kernel-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_dense_1_dense_kernel-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_29; Type: Shape; Out #tensors:  1",
    "Name: Const_85; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_dense_1_dense_kernel-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_dense_1_dense_kernel-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_dense_1_dense_kernel-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_30; Type: Shape; Out #tensors:  1",
    "Name: Const_86; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_dense_1_dense_bias-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_dense_1_dense_bias-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_dense_1_dense_bias-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_31; Type: Shape; Out #tensors:  1",
    "Name: Const_87; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_dense_1_dense_bias-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_dense_1_dense_bias-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_dense_1_dense_bias-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_32; Type: Shape; Out #tensors:  1",
    "Name: Const_88; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_dense_2_dense_kernel-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_dense_2_dense_kernel-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_dense_2_dense_kernel-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_33; Type: Shape; Out #tensors:  1",
    "Name: Const_89; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_dense_2_dense_kernel-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_dense_2_dense_kernel-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_dense_2_dense_kernel-v; Type: Assign; Out #tensors:  1",
    "Name: Shape_34; Type: Shape; Out #tensors:  1",
    "Name: Const_90; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_dense_2_dense_bias-m; Type: Fill; Out #tensors:  1",
    "Name: optimizer_dense_2_dense_bias-m; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_dense_2_dense_bias-m; Type: Assign; Out #tensors:  1",
    "Name: Shape_35; Type: Shape; Out #tensors:  1",
    "Name: Const_91; Type: Const; Out #tensors:  1",
    "Name: Init_optimizer_dense_2_dense_bias-v; Type: Fill; Out #tensors:  1",
    "Name: optimizer_dense_2_dense_bias-v; Type: VariableV2; Out #tensors:  1",
    "Name: Assign_optimizer_dense_2_dense_bias-v; Type: Assign; Out #tensors:  1",
    "Name: optimizer_beta1_power; Type: VariableV2; Out #tensors:  1",
    "Name: Init_optimizer_beta1_power; Type: Const; Out #tensors:  1",
    "Name: Assign_optimizer_beta1_power; Type: Assign; Out #tensors:  1",
    "Name: optimizer_beta2_power; Type: VariableV2; Out #tensors:  1",
    "Name: Init_optimizer_beta2_power; Type: Const; Out #tensors:  1",
    "Name: Assign_optimizer_beta2_power; Type: Assign; Out #tensors:  1",
    "Name: Const_92; Type: Const; Out #tensors:  1",
    "Name: Const_93; Type: Const; Out #tensors:  1",
    "Name: Const_94; Type: Const; Out #tensors:  1",
    "Name: Const_95; Type: Const; Out #tensors:  1",
    "Name: ApplyAdam; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_1; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_2; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_3; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_4; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_5; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_6; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_7; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_8; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_9; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_10; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_11; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_12; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_13; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_14; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_15; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_16; Type: ApplyAdam; Out #tensors:  1",
    "Name: ApplyAdam_17; Type: ApplyAdam; Out #tensors:  1",
    "Name: Mul; Type: Mul; Out #tensors:  1",
    "Name: Assign; Type: Assign; Out #tensors:  1",
    "Name: Mul_1; Type: Mul; Out #tensors:  1",
    "Name: Assign_1; Type: Assign; Out #tensors:  1",
    "Name: default_output; Type: Softmax; Out #tensors:  1",
    "Name: Const_96; Type: Const; Out #tensors:  1",
    "Name: ArgMax; Type: ArgMax; Out #tensors:  1",
    "Name: Const_97; Type: Const; Out #tensors:  1",
    "Name: ArgMax_1; Type: ArgMax; Out #tensors:  1",
    "Name: Equal; Type: Equal; Out #tensors:  1",
    "Name: Cast_16; Type: Cast; Out #tensors:  1",
    "Name: Const_98; Type: Const; Out #tensors:  1",
    "Name: Mean_2; Type: Mean; Out #tensors:  1",
    ""
)
